Repository pivotal-cf/cf-rabbitmq-release, pull requests merged in 2020-10, with the labels that each got.

#386 Update readme CI builds and install instructions.
  README.md
Labels: in progress

#388 Update travis config.
  .travis.yml
Labels: unscheduled

#387 Capture `cd` exit code and fail when in unreadable dir.
  src/rabbitmq-server/rabbitmq-script-wrapper
Labels: unscheduled

#391 Update vendored Go modules for pivotal-cf/cf-rabbitmq-release
  src/rabbitmq-upgrade-preparation/go.mod
  src/rabbitmq-upgrade-preparation/go.sum
  src/rabbitmq-upgrade-preparation/vendor/github.com/nxadm/tail/.travis.yml
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/fcntl_darwin.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/gccgo.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/gccgo_c.c
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/mkerrors.sh
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/sockcmsg_unix_other.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_bsd.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_darwin.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_freebsd.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_illumos.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_linux.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_netbsd.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_openbsd.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_darwin_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_darwin_arm.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_386.s
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm.s
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_illumos_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_linux.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_darwin_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_darwin_arm.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_linux.go
  src/rabbitmq-upgrade-preparation/vendor/modules.txt
Labels: unscheduled

#390 Update vendored Go modules for pivotal-cf/cf-rabbitmq-release
  src/rabbitmq-admin/go.mod
  src/rabbitmq-admin/go.sum
  src/rabbitmq-admin/vendor/github.com/nxadm/tail/.travis.yml
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/fcntl_darwin.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/gccgo.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/gccgo_c.c
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/mkerrors.sh
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/sockcmsg_unix_other.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/syscall_bsd.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/syscall_darwin.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/syscall_freebsd.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/syscall_illumos.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/syscall_linux.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/syscall_netbsd.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/syscall_openbsd.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_darwin_386.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_darwin_arm.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_darwin_386.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_darwin_386.s
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm.s
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_illumos_amd64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/zsyscall_linux.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/ztypes_darwin_386.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/ztypes_darwin_arm.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/unix/ztypes_linux.go
  src/rabbitmq-admin/vendor/golang.org/x/sys/windows/service.go
  src/rabbitmq-admin/vendor/modules.txt
Labels: unscheduled

#392 Render STOMP-over-WebSockets SSL config
  jobs/rabbitmq-server/templates/rabbitmq.conf.erb
  spec/unit/templates/rabbitmq_conf_spec.rb
Labels: unscheduled

#389 Update erlang-23 package
  config/blobs.yml
  packages/erlang-23/packaging
  packages/erlang-23/spec
Labels: unscheduled

#393 Clean up bash and most shellcheck errors.
  jobs/rabbitmq-server/templates/add-rabbitmqctl-to-path.bash
  jobs/rabbitmq-server/templates/cluster-check.bash
  jobs/rabbitmq-server/templates/drain.bash
  jobs/rabbitmq-server/templates/pre-start.bash
  jobs/rabbitmq-server/templates/pre-stop.bash.erb
  jobs/rabbitmq-server/templates/prepare-for-upgrade.bash
  jobs/rabbitmq-server/templates/rabbitmq-server.init.bash
  jobs/rabbitmq-server/templates/setup.bash
Labels: hacktoberfest-accepted, unscheduled

#394 Fix incorrect disable_non_ssl_listeners behaviour
  jobs/rabbitmq-server/templates/setup.bash
  spec/bash/setup_test.bash
Labels: unscheduled

#396 Update golang package
  config/blobs.yml
  packages/golang/packaging
  packages/golang/spec
Labels: unscheduled

#398 Update vendored Go modules for pivotal-cf/cf-rabbitmq-release
  src/rabbitmq-upgrade-preparation/go.mod
  src/rabbitmq-upgrade-preparation/go.sum
  src/rabbitmq-upgrade-preparation/vendor/github.com/onsi/ginkgo/CHANGELOG.md
  src/rabbitmq-upgrade-preparation/vendor/github.com/onsi/ginkgo/config/config.go
  src/rabbitmq-upgrade-preparation/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  src/rabbitmq-upgrade-preparation/vendor/github.com/onsi/ginkgo/internal/testingtproxy/testing_t_proxy.go
  src/rabbitmq-upgrade-preparation/vendor/github.com/onsi/gomega/.travis.yml
  src/rabbitmq-upgrade-preparation/vendor/github.com/onsi/gomega/CHANGELOG.md
  src/rabbitmq-upgrade-preparation/vendor/github.com/onsi/gomega/go.mod
  src/rabbitmq-upgrade-preparation/vendor/github.com/onsi/gomega/go.sum
  src/rabbitmq-upgrade-preparation/vendor/github.com/onsi/gomega/gomega_dsl.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/net/html/const.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/net/html/render.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/fcntl_linux_32bit.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/mkerrors.sh
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_aix.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_darwin.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_darwin_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_darwin_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_darwin_arm.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_darwin_arm64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_linux.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_linux_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/syscall_solaris.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_darwin_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_darwin_arm.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_dragonfly_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_linux.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zerrors_solaris_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_386.s
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsyscall_dragonfly_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_dragonfly_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_darwin_386.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_darwin_arm.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_dragonfly_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_linux.go
  src/rabbitmq-upgrade-preparation/vendor/golang.org/x/sys/unix/ztypes_solaris_amd64.go
  src/rabbitmq-upgrade-preparation/vendor/modules.txt
Labels: unscheduled
